export { default as Home } from './Home/Home'
export { default as Product } from './Product/Product'
export { default as SignIn } from './SignIn/SignIn'
export { default as Register } from './Register/Register'
export { default as CheckoutSuccess } from './Checkout/CheckoutSuccess'
export { default as Cart } from './Cart/Cart'
export { default as Profile } from './Profile/Profile'
export { default as Order } from './Order/Order'
